export const Errors = {
  INVALID_OR_MISSING_ID: 'INVALID_OR_MISSING_ID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
}

export const Success = {
  USER_CREATED: 'USER_CREATED',
}
